name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
        config:
          - ""
          - --disable-curses
          - --disable-lua
          - --disable-tre
          - --disable-selinux
          - --disable-acl
          - --disable-help
    runs-on: ${{ matrix.os }}
    env:
      CFLAGS_EXTRA: --coverage
      LDFLAGS_EXTRA: --coverage
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Dependency
      run: |
        sudo apt install \
          9base \
          libacl1-dev \
          liblua5.3-dev \
          libncursesw5-dev \
          libselinux1-dev \
          libtermkey-dev \
          libtre-dev \
          lua-lpeg

    - name: Build
      run: |
        ./configure ${{ matrix.config }}
        make

    - name: Test
      run: |
        make test

    - name: Upload Test Coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        curl -s https://codecov.io/bash > codecov
        curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/SHA256SUM > codecov.sha256
        if ! sha256sum -c --ignore-missing --status codecov.sha256 ; then
          echo "Download checksum verification failed"
          exit 1
        fi
        bash < codecov
